:toc: toc::[]

Economics

This document describes principles, models, theories, and systems in economics. For information specific to historic time-periods, see files under 'Society'.

TODO: This document needs work.

= Fundamentals

* Summary of US economic history – Paradigm shifts by Dalio :https://economicprinciples.org/downloads/Paradigm-Shifts.pdf

= Monetary System

== Principles

* Money is the universal commodity. Fiat.
* Money moves around economy is search of returns.
* Amount of money determined by monetary system. More = volatility.
* System must absorb money just as power grid absorbs electricity.
* Ex: If money floods system, everything is more expensive, people are poorer, unclear if money is spread equally, unclear if people can afford expensive goods, eventually goods don’t sell and default. A series of debts are owed. To unwind debts, govt steps in.
* Therefore, banks + reserve + govt steward monetary system.
* If central banks print money,
** Then that creates the illusion of wealth.
** However, inflation increases, asset prices increases etc hence the illusion.
** To keep the illusion, central banks must keep printing -> runaway.
** Instead, productivity must rise for actual progress.
** However, printing money helps get monetary system going away; otherwise, people are too afraid to lend.

== International Monetary System

2018 https://www.stlouisfed.org/publications/regional-economist/third-quarter-2018/understanding-roots-trade-deficit[source]
* After World War II, a new international monetary system called Bretton Woods was created that would draw lessons from the previous gold standards abandoned after World War I and the experiences of the Great Depression. Bretton Woods established (1) the U.S. dollar was to be an international reserve currency, (2) the U.S. dollar would be backed by gold at a price of $35 per ounce, and (3) any country could exchange dollars for gold. This new system facilitated and stabilized global trade, especially trade among the industrialized nations.
* However, after years of expansionary growth in U.S. aggregate demand in the 1960s, countries running trade surpluses with the U.S. sought to exchange their dollars for gold, which rapidly shrunk U.S. gold reserves. The U.S. then ran the risk of failing to meet its obligation to redeem dollars for gold at the official price. Thus, President Richard Nixon effectively ended the Bretton Woods system in 1971.1
* The U.S. decision to end dollar convertibility to gold and the subsequent collapse of the Bretton Woods system in the early 1970s meant that the world economy entered a new era: The U.S. dollar became the global currency, and U.S. government securities became the most-demanded foreign reserve in the world. This outcome resulted from the historical strength of the U.S. currency. Consequently, the dollar became as good as gold (despite the fact that it is a fiat currency), which fuels demand for U.S. currency and securities to be used both as an international medium of exchange and store of value.
* When the U.S. can purchase goods from the world market simply by printing money or issuing debt, it is destined to run persistent trade deficits. Indeed, just a few years after the end of the Bretton Woods system, the U.S. trade balance started to show persistent and growing deficits, which continue today.

2019 https://fas.org/sgp/crs/row/IF10619.pdf[source]
* The dollar, as a de facto global reserve currency, facilitates the trade deficit by broadening the availability of dollars and dollar-denominate assets. Without this unique role, the United States would have faced major challenges sustaining trade deficits without making domestic economic adjustments.

== Money Needs Institutional Backing

* https://ftalphaville.ft.com/2019/09/02/1567428778000/ECB-board-member-slams–cartel-like–libra/
** Facebook’s proposed currency is a chance to finally deploy the arguments that people who hate central banks deploy against you all the time.
** money needs state sovereignty to be ``credible and durable'' – which raises the question of what kind of state we’re talking about.
** Conglomerates of corporate entities, he adds, ``are only accountable to their shareholders and members''. Such conglomerates ``can hardly be seen as repositories of public trust or legitimate issuers of instruments with the attributes of “money''.

== Money supply + interest rates

* LIBOR fixing scandal –
** banks were falsely inflating or deflating their rates so as to profit from trades, or to give the impression that they were more creditworthy than they were
** public and private financial institutions manipulating interest rates to prop up the prices of bonds and other fixed income instruments, and that ``the motives of the Fed, Bank of England, US and UK banks are aligned, their policies mutually reinforcing and beneficial. The Libor fixing is another indication of this collusion.'' [https://web.archive.org/web/20130805221036/http://www.paulcraigroberts.org/2012/07/14/the-real-libor-scandal/[source]]

== Bubbles

TODO: Clean up the following points.
* People borrow on expectation of returns.
* If returns don’t materialize, you get default and bubble.
* Central banks can print to inflate away debt and absorb bubble but that causes inflation.
* A sector can be out of sync, such as housing or tech, because of sector-specific expectations of high returns.
* Therefore, bubbles result from society processing information to arrive at incorrect predictions of the future. Recessions reconcile incorrect predictions with reality.

* https://scholar.harvard.edu/files/shleifer/files/bffs_20170217.pdf[source]
** Our broad conclusion is one that historians – particularly Kindleberger -- have reached already. There is much more to a bubble than a mere security price increase. There is innovation, displacement of existing firms, creation of new ones, and more generally a “paradigm shift” as entrepreneurs and investors rush toward a new Eldorado. Our contribution is to show that this shift is to some extent measurable in financial data.
** we look at all episodes since 1928 in which stock prices of a US industry have increased over 100% in terms of both raw and net of market returns over the previous two years. We identify 40 such episodes in US data. We examine the characteristics of these portfolios as well as their performance going forward, just as Fama recommends. We then repeat the exercise for international sector portfolios between 1987 and 2013 to see if the US findings obtain out of sample.
** a sharp price increase of an industry portfolio does not, on average, predict unusually low returns going forward. Average returns following a price run-up approximately match those of the broader market in the following two years, and are unremarkable in raw terms as well.
** Health sector stocks rose by over 100% between April 1976 and April 1978, and continued going up by more than 65% per year on average in the next three years, not experiencing a significant drawdown until 1981.
** sharp price increases do predict a heightened likelihood of a crash. More importantly, returns are in fact predictable, since there are other attributes of well-performing portfolios that in fact help distinguish portfolios that earn low and high returns going forward. Based on this information, there are times when one can call a bubble with some confidence.

== Steady state

* As productivity increases, the same amount of money buys more.
* Hence, real increase in wealth without resort to money printing.

= Taxation

* https://en.wikipedia.org/wiki/Land_value_tax[Land value tax] taxes the unimproved value of land and is generally favored by economists as (unlike other taxes) it does not cause economic inefficiency, and it tends to reduce inequality.

= xComplexity

== Monetary Policy

* The more complex the system, the harder for agents to predict the future, and for agents to see the gap between prediction and reality. Hence, complexity obfuscates the true nature of problems, leading to bubbles going unnoticed.
* Further, central banks or politicians might incorrectly diagnose bubbles as fundamental problems and try to monetize debt, or print money to stimulate the economy.

== Internationalization

* International money flows add noise
* High savings countries chase returns
* Global rich
* Capital controls
* Hawala

= Case Study: Great Recession 2008

* A financialised economy will have a thriving banking system, but it will also be characterised by rising household and corporate debt, soaring asset prices, huge capital inflows, deindustrialisation and growing income, wealth and regional inequality.
* In the US and the UK, the deregulation of commercial banking and the removal of restrictions on capital mobility led to a lending boom in the 1980s. Banks faced far fewer restrictions on their ability to create money by extending credit, and mortgage lending in particular soared.
* As the money directed into property markets increased faster than the housing stock, property prices boomed. Rising house prices allowed consumers to borrow even more by releasing the equity from their homes.
* Capital from all over the world flowed into British and American property and financial markets, pushing up the value of the currency and harming exporters. As tax revenues from the sector flowed into Treasury coffers, the state’s willingness to regulate it waned.
* Economists failed to pay attention to any of these indicators before the crash, instead dubbing the period between 1989 and 2007 the ``great moderation'' — a time of high growth, low inflation and generalised economic and financial stability. Only when the boom finally ended did they realise the veneer of moderation had concealed a wellspring of excess.
* But the financial crisis did not spell the end of financialisation — instead, it heralded another phase of its expansion. Since the financial crisis, property prices in Sydney and Melbourne have risen 105 per cent and 94 per cent respectively. Private debt-to-GDP, which includes all household and corporate debt, has increased from 184 per cent of GDP in 2010 to 205 per cent today. Household debt is more than 200 per cent of average incomes, making Australian households some of the most indebted in the world. +
* https://www.newstatesman.com/world/australasia/2019/06/australia-s-property-bubble-shows-lessons-2008-crash-havent-been-learned
