:toc:
toc::[]

## Universality of Human Condition

*   Chagnon on yamomamo: [source](https://www.edge.org/conversation/napoleon-chagnon-blood-is-their-argument) The villages that I became really involved in, like Bisaasi-teri and these were just like my good friends, and even some of my relatives, and it was not like observer-observed kind of relationship. I wept at their funerals, and things like that. They played with my kids in the short time my kids were there. So it's very easy to empathize and recognize, even as an anthropologist or maybe a missionary, how similar these people are to you. They may have exotic customs, and eat grubs an inch long, but basically, when you scratch them, they bleed red and have emotions like yours.

## Language

*   [Source](edge.org/conversation/napoleon-chagnon-blood-is-their-argument)
    *   DENNETT:  Haha. In your book you mention that, although they have words, the idea of a word was not obvious to them, and that you had to go through some effort to get them to break their language up into their words, into nouns, verbs, and so forth.
    *   CHAGNON:  You must have read something I wrote about this, because that's exactly what happened. The biggest difficulty I faced in doing my field research is to get them to realize the notion of a word and where one ended and the next one began. They intuitively knew that, but they didn't know how to explain that to me. They'd make a statement to me that would go on for five pages, and it was because I didn't know where one part of the statement ended and the next began. And I finally trained one of them, right, got one of them to understand what I was trying to do. I wanted him to say a word as a discrete component in a more complex collection of words, and I thought this was a major breakthrough, and it was.
    *   PINKER:  That's true in non-literate peoples in general, and in children. , What intuitively seems to us like a word is actually the product of  active meta-linguistic awareness:  reflecting back on language as an entity.  Until the late Middle Ages there weren't even spaces between words in print. Language was just written as one long sequence of sounds, which literally is what it is. If you look at an oscilloscope tracing of speech there are no little breaks between one word and the other.

## Emotions

### Happiness

*   Competition mandates a general level of unhappiness
*   You can’t opt of competition unless you can let go of desire (meditation). However, you probably do actually want those things and need a balance. Otherwise, negative consequences.
    *   https://en.wikipedia.org/wiki/Diderot_effect
*   This is not a bad thing. Negative emotions, such as stress and dissatisfaction, drive change that makes you better

### Motivation vs Laziness

*   Man goes to extraordinary lengths to invent adrenal surgery over 11 years to cure chronic condition. If he didn’t have this condition, he’d have done what everyone else does -- BBQ, church, kids: https://fox5sandiego.com/2019/07/27/man-cures-himself-after-being-bedridden-11-years/

## Psyche & Technology

### Need for Belonging

*   Social Surrogacy Hypothesis https://www.scientificamerican.com/article/imaginary-friends/
    *   http://dx.doi.org/10.1016/j.jesp.2008.12.003
    *   Jaye Derrick and [Shira Gabriel](http://wings.buffalo.edu/psychology/people/faculty/gabriel.html) of the University of Buffalo and [Kurt Hugenberg](http://www.units.muohio.edu/psychology/people/hugenbk.html) of Miami University test what they call the “Social Surrogacy Hypothesis.”
    *   It appears that experiencing a lack of belonging actually caused people to revel in their favorite TV shows, as though the parasocial relationships with TV characters replaced the flawed relationships that had been recalled.

## Leaders, Politicians, Dictators

### Politicians Managing Reputations

*   [dead cat maneuver](https://twitter.com/AdamBienkov/status/1143585761842933760): if you've been caught out doing something terrible, just throw a dead cat in the middle of the dining room table. People will still be angry at you, but they'll be angry at you about the dead cat, not about the thing you were trying to bury. For example: Prior to the model-bus interview, if you googled "boris johnson bus" you would learn about [Johnson's infamous "Brexit Battle Bus"](https://boingboing.net/2017/07/05/referendumb.html) which was driven around the UK in the runup to the Brexit vote. Today, the results are a mix of stories about the model bus hobby and the Brexit bus (as well as stories about whether this was a media manipulation gambit). This is such a brilliant example of political search engine optimization that it's hard to believe someone as buffoonish as Johnson would be capable of pulling it off intentionally.

### Organizational Trust

*   Face to face time, talking enough
*   Allow chats bferoe/after meetings

## Innovation & Decision Making

*   Peer pressure speeds decision making: PP can overcome barriers imposed upon a consensus by the existence of tightly connected communities with local leaders or the existence of leaders with poor cohesiveness of opinions. A moderate level of PP is also necessary to explain the rate at which innovations diffuse through a variety of social groups. How Peer Pressure Shapes Consensus, Leadership, and Innovations in Social Groups https://www.nature.com/articles/srep02905?WT.ec_id=SREP-20131015 
*   Tight groups of deep domain knowledge, messing around, obsession
    *   Homebrew computer club
    *   Fairchildt five
    *   Dirac on quantum mechanics -- we were just messing around
    *   Groups of two
        *   Jeff Dean and Sanjay Ghemawat, 
        *   Amos Tversky and Daniel Kahneman
    *   Patagonia+North Face: Mountain of Storms: Before they were magnates of the outdoors, Patagonia founder Yvon Chouinard and The North Face’s co-founder Doug Tompkins, in 1968, they and three friends — now-famous rock climber Chris Jones, U.S. ski/snowboard Hall of Famer Dick Dorworth, and Mountainfilm founder Lito Tejada-Flores — set off from San Francisco to Patagonia.
    *   Hao Huang proved sensitivity conjecture -- [ref](https://www.quantamagazine.org/mathematician-solves-computer-science-conjecture-in-two-pages-20190725/) -- Hao learned problem in 2012 and solved in 2019 -- starting in 2013 he conjectured a new approach and thought about approach for 5 years -- 2018 he had a brainwave about a leveraging Cauchy interlace theorem -- finally brainwave in 2019.

## How Thoughts Evolve

*   Initially, people should do whatever they want as long as they aren't hurting other people-- that doesn't mean anything -- the world is complex
*   If you’re young and not a socialist you have no heart, if you’re old and not a convervative have no brain.

## Machine Learning

*   Reservoir computing for predicting dynamical systems: A neural network acts as a “reservoir” that abstracts the higher-dimensional state of a dynamical system into a lower-dimensional state.