= Cognitive Science

== Predictive Coding

* Ref: https://www.ncbi.nlm.nih.gov/pubmed/23663408
* Surprisal – What needs to be transmitted is therefore just the difference (a.k.a. the ``prediction error'') between the actual current signal and the predicted one. This affords major savings on bandwidth – this makes prediction error into a kind of proxy (Feldman & Friston 2010) for sensory information itself – prediction error reports the ``surprise'' induced by a mismatch between the sensory signals encountered and those predicted. More formally – and to distinguish it from surprise in the normal, experientially loaded sense – this is known as surprisal
** Prediction and error-correction cycles occur concurrently throughout the hierarchy, so top-down information influences lower-level estimates, and bottom-up information influences higher-level estimates of the input signal.
* Example – Visual system – Ganglion cells perform anti-Hebbian feedforward learning, in which correlated activity across units leads to inhibition rather than to activation (see, e.g., Kohonen 1989), enables the creation of ``novelty filters'' that learn to become insensitive to the most highly correlated (hence most ``familiar'') features of the input.
** When each eye is presented with a different image, These errors are then propagated up the system. To explain them away the overall interpretation must switch. This pattern repeats, yielding the distinctive alternations experienced during dichoptic viewing of inconsistent stimuli.
* Actions – you treat the desired (goal) state as observed and perform Bayesian inference to find the actions that get you there. This mapping between perception and action emerges also in some recent work on planning (e.g., Toussaint 2009). The idea, closely related to these approaches to simple movement control, is that in planning we imagine a future goal state as actual, then use Bayesian inference to find the set of intermediate states (which can now themselves be whole actions) that get us there. There is thus emerging a fundamentally unified set of computational models which, as Toussaint (2009, p. 29) comments, ``does not distinguish between the problems of sensor processing, motor control, or planning.''
* Information-theoretic free energy – Free energy is the energy available to do useful work. Transposed to the cognitive/informational domain, it emerges as the difference between the way the world is represented as being, and the way it actually is. The better the fit, the lower the information-theoretic free energy (this is intuitive, since more of the system’s resources are being put to ``effective work'' in representing the world). Prediction error reports this information-theoretic free energy, which is mathematically constructed so as always to be greater than ``surprisal'' (where this names the sub-personally computed implausibility of some sensory state given a model of the world – see Tribus (1961) and sect. 4.1 in the present article). Entropy, in this information-theoretic rendition, is the long-term average of surprisal, and reducing information-theoretic free energy amounts to improving the world model so as to reduce prediction errors, hence reducing surprisal14 (since better models make better predictions). The overarching rationale (Friston 2010) is that good models help us to maintain our structure and organization, hence (over extended but finite timescales) to appear to resist increases in entropy and the second law of thermodynamics. They do so by rendering us good predictors of sensory unfoldings, hence better poised to avoid damaging exchanges with the environment
* Schizophrenia – Malfunctions within that complex economy (perhaps fundamentally rooted in abnormal dopaminergic functioning) yield wave upon wave of persistent and highly weighted ``false errors'' that then propagate all the way up the hierarchy forcing, in severe cases (via the ensuing waves of neural plasticity) extremely deep revisions in our model of the world. The improbable (telepathy, conspiracy, persecution, etc.) then becomes the least surprising, and – because perception is itself conditioned by the top-down flow of prior expectations – the cascade of misinformation reaches back down, allowing false perceptions and bizarre beliefs to solidify into a coherent and mutually supportive cycle
* Attention fts very neatly into this emerging unified picture, as a means of variably balancing the potent interactions between top-down and bottom-up influences by factoring in their precision (degree of uncertainty). This is achieved by altering the gain (the ``volume,'' to use a common analogy) on the error-units accordingly. The upshot of this is to ``control the relative influence of prior expectations at different levels'' (Friston 2009, p. 299). In recent work, effects of the neurotransmitter dopamine are presented as one possible neural mechanism for encoding precision (see Fletcher & Frith [2009, pp. 53–54] who refer the reader to work on prediction error and the mesolimbic dopaminergic system such as Holleman & Schultz 1998; Waelti et al. 2001). Greater precision (however encoded) means less uncertainty, and is reflected in a higher gain on the relevant error units (see Friston 2005; 2010; Friston et al. 2009). Attention, if this is correct, is simply one means by which certain error-unit responses are given increased weight, hence becoming more apt to drive learning and plasticity, and to engage compensatory action.

== Brain Development

* https://www.cambridgebrainsciences.com/more/articles/how-superagers-maintain-cognitive-performance-into-their-80s[Superagers] – refers to an older adult whose cognitive performance is the same as a younger adult. Felicia Sun et al., published in the Journal of Neuroscience, looked at the neuroanatomy of older adults, and found that key regions of the brain had higher cortical thickness among superagers, compared to adults who aged normally. To become a superager, Lisa Feldman Barrett (one of the authors of the study above) speculates that it takes both physical and mental activity, and it has to be difficult.
* ``engaging your child in conversation (versus just flooding them with exposure to words) is critical to language and brain development,'' – [https://www.inc.com/scott-mautz/harvard-mit-study-says-doing-1-simple-thing-is-almost-magical-for-your-childs-brain-development-success.html[popsci ref]] [https://journals.sagepub.com/doi/abs/10.1177/0956797617742725[paper]] – ``children who had experienced more conversational turns with adults exhibited greater left inferior frontal (Broca’s area) activation''

== Imitation

*   https://unix.stackexchange.com/questions/1645/is-there-any-option-with-ls-command-that-i-see-only-the-directories[Source]
There is vast agreement among ethologists that imitation, the capacity
to learn to do an action from seeing it done (Thorndyke 1898), is
present among primates, only in humans, and (probably) in apes (see
Byrne 1995, Galef 1988, Tomasello & Call 1997, Visalberghi & Fragaszy
2001, Whiten & Ham 1992).  Therefore, the primary function of mirror
neurons cannot be action imitation. See secton on [Mirror Neurons].

== Mirror Neurons

https://unix.stackexchange.com/questions/1645/is-there-any-option-with-ls-command-that-i-see-only-the-directories[Source]
* Mirror neurons are a particular class of visuomotor neurons,
originally discovered in area F5 of the monkey premotor cortex, that
discharge both when the monkey does a particular action and when it
observes anotherindividual(monkey or human) doing a similar action (Di
Pellegrino et al. 1992, Gallese et al. 1996, Rizzolatti et al. 1996a).
** Two main hypotheses
*** Mirror-neuron activity mediates imitation (see
Jeannerod 1994). Thus, the mirror system transforms visual information into knowledge (see Rizzolatti et al.
2001). Each time an individual sees an action done by another individual, neurons that represent that action are activated in the
observer’s premotor cortex. This automatically induced, motor representation of the observed action corresponds to that which is spontaneously generated during
active action and whose outcome is known to the acting individual.
*** Mirror neurons are at the basis of action
understanding (see Rizzolatti et al. 2001). Though, mirror neurons are not the only mechanism for action understanding. The visual features of the observed actions
are fundamental to trigger mirror neurons only insomuch as they allow the understanding of the observed actions. If action comprehension is possible on another
basis (e.g., action sound), mirror neurons signal the action, even in the absence of
visual stimuli.
*  TMS studies indicate that a mirror-neuron system (a motor resonance system) exists in humans and that it possesses important properties not
observed in monkeys. First, intransitive meaningless movements produce mirrorneuron system activation in humans(Fadiga et al. 1995, Maeda et al. 2002, Patuzzo
et al. 2003), whereas they do not activate mirror neurons in monkeys. Second, the
temporal characteristics of cortical excitability, during action observation, suggest
that human mirror-neuron systems code also for the movements forming an action
and not only for action as monkey mirror-neuron systems do. These properties of
the human mirror-neuron system should play an important role in determining the
humans’ capacity to imitate others’ action.
