= Language

== Concept of Words

* link:edge.org/conversation/napoleon-chagnon-blood-is-their-argument[Source]
** DENNETT: Haha. In your book you mention that, although they have words, the idea of a word was not obvious to them, and that you had to go through some effort to get them to break their language up into their words, into nouns, verbs, and so forth.
** CHAGNON: You must have read something I wrote about this, because that’s exactly what happened. The biggest difficulty I faced in doing my field research is to get them to realize the notion of a word and where one ended and the next one began. They intuitively knew that, but they didn’t know how to explain that to me. They’d make a statement to me that would go on for five pages, and it was because I didn’t know where one part of the statement ended and the next began. And I finally trained one of them, right, got one of them to understand what I was trying to do. I wanted him to say a word as a discrete component in a more complex collection of words, and I thought this was a major breakthrough, and it was.
** PINKER: That’s true in non-literate peoples in general, and in children. , What intuitively seems to us like a word is actually the product of active meta-linguistic awareness: reflecting back on language as an entity. Until the late Middle Ages there weren’t even spaces between words in print. Language was just written as one long sequence of sounds, which literally is what it is. If you look at an oscilloscope tracing of speech there are no little breaks between one word and the other.

== Oral vs. Written Language

* https://www.researchgate.net/profile/Patricia_Greenfield/publication/18511965_Oral_or_Written_Language_the_Consequences_for_Cognitive_Development_in_Africa_the_United_States_and_England/links/5dfd5755299bf10bc36bbd55/Oral-or-Written-Language-the-Consequences-for-Cognitive-Development-in-Africa-the-United-States-and-England.pdf[source] 
** If the speaker of an oral language depends upon the surrounding context to communicate his message, then effective communication presupposes a common context and common point of view for both listener and speaker. The speaker, moreover, mustassume that this is the case. He is, therefore, egocentric; that is, he takes for granted, without being aware of doing so, that his point of view and frame of reference are the only possible ones. At times, this assumption may be valid, at other times, not so.
** Why should contextuality characterize the use of oral languages more so than that of written? First, in an oral culture, communication is invariably face to face. Consequently, the assumption of a common physical context is a valid one. Second, oral languages generally do not spread as far as written languages and are therefore shared by smaller groups. For this reason, the assumption of a common psychological point of view is a realistic one. In consequence, context-dependent speech works.
** Speech based on a written language, in contrast, must be relatively independent of context for a number of reasons. An important one is that written cultures usually cover larger geographic areas and therefore encompass more heterogeneous people. Consequently, the assumption of a common frame of reference will often be invalid even where contact is face to face.
** Hess and Shipman’s (1965) data- on maternal teaching styles are relevant here. One hundred and sixty black American mothers from four socio-economic levels were taught two classificatory tasks and then observed as they taught these tasks to their four-year-old children.  A presumably typical middle-class mother gave explicit instructions for the colour sorting task, including statements like: The things that are all the same colour you put in one section, in the second section you put another group of colours, and in the third section you put the last group of colours. Contrast now a lower-class mother’s explanation: All right, just put them right here; put the other one right here; all right, put the other one here. She is explaining by demonstration. What is important for the present discussion is that the meaning of her verbalization is totally dependent on the concrete physical situation. 
