Psychology

= Universality of Human Condition

* Chagnon on yamomamo: https://www.edge.org/conversation/napoleon-chagnon-blood-is-their-argument[source] The villages that I became really involved in, like Bisaasi-teri and these were just like my good friends, and even some of my relatives, and it was not like observer-observed kind of relationship. I wept at their funerals, and things like that. They played with my kids in the short time my kids were there. So it’s very easy to empathize and recognize, even as an anthropologist or maybe a missionary, how similar these people are to you. They may have exotic customs, and eat grubs an inch long, but basically, when you scratch them, they bleed red and have emotions like yours.
*  https://www.nature.com/articles/d41586-020-03509-5[Source]
** The universality hypothesis proposes that people around the world consistently use certain configurations of facial-muscle movements to specifically express instances of a certain category of emotion. For example, people are said to frown in sadness consistently enough (and frown infrequently at other times) for frowning to be recognized as the expression of sadness the world over.
** There is considerable debate about whether the published empirical evidence provides support for the universality hypothesis. A large body of literature seems to back it up, but these studies have been consistently criticized for methodological problems4,5. Furthermore, a growing number of experiments (both in modern, urban populations5 and in small-scale foraging communities6, such as the Hadza hunter-gatherer group in Tanzania7) using diverse methods seem to call the universality hypothesis into doubt. This research suggests that expressions of emotion might be context-specific, and therefore variable across instances — the facial movements in each instance being tailored to the immediate context, as is the case for all other motor movements. In fact, study after study has revealed the potent influence of context on both how people move their faces to express emotion and how other people infer emotional meaning in those facial movements5,8,9.

= Meaning

== Meaning Comes from Struggle
* [Born Rich](https://youtu.be/1sD3pG74Wv8?t=1844) at 30:43: "*Really, what I learned, is that working hard makes me happy."
** [At 33:10](https://youtu.be/1sD3pG74Wv8?t=1990): "*People with money that don't do anything aren't happy*"

= Intelligence

* Intelligence has two aspects: fluid and crystallized.
* Intelligence, or IQ, is a replicable test. IQ is the best predictor of life outcome.
* More intelligent brains show faster nerve conduction, less glucose utilization in positron emission tomography, faster reaction times (RTs), faster inspection times, faster speeds in general, and greater circumference and volume. Observations concerning intelligence could be explained if much variance in intelligence reflects myelination differences. See Miller, E. M. (1994). Intelligence and brain myelination: A hypothesis.

= Big Five

== Conscientiousness

* https://monoskop.org/images/4/41/Malinowski_Bronislaw_Magic_Science_and_Religion_and_Other_Essays_1948.pdf[Source]
** Hard work in Melanesians: "Melanesians who inhabit the coral atolls to the N.E. of the main island, the Trobriand Archipelago and the adjoining groups, are expert fishermen, industrious manufacturers and traders, but they rely mainly on gardening for their subsistence. With the most rudimentary implements, a pointed digging-stick and a small axe, they are able to raise crops sufficient to maintain a dense population and even yielding a surplus, which in olden days was allowed to rot unconsumed, and which at present is exported to feed plantation hands. The success in their agriculture depends -- besides the excellent natural conditions with which they are favored -- upon their extensive knowledge of the classes of the soil, of the various cultivated plants, of the mutual adaptation of these two factors, and, last not least, upon their knowledge of the importance of accurate and hard work. They have to select the soil and the seedlings, they have appropriately to fix the times for clearing and burning the scrub, for planting and weeding, for training the vines of the yam plants. [MB 28] In all this they are guided by a clear knowledge of weather and seasons, plants and pests, soil and tubers, and by a conviction that this knowledge is true and reliable, that it can be counted upon and must be scrupulously obeyed."

= Emotions

== Happiness

* Competition mandates a general level of unhappiness
* You can’t opt of competition unless you can let go of desire (meditation). However, you probably do actually want those things and need a balance. Otherwise, negative consequences.
** https://en.wikipedia.org/wiki/Diderot_effect
* This is not a bad thing. Negative emotions, such as stress and dissatisfaction, drive change that makes you better
* People of an upbeat disposition have previously been found to have a lower risk of heart conditions and premature death. Researchers now say it could also play a role in living a long life. The team behind the study say their findings could also be cause for cheer. `A lot of evidence suggests that exceptional longevity is usually accompanied by a longer span of good health and living without disability, so our findings raise an exciting possibility that we may be able to promote healthy and resilient ageing by cultivating psychosocial assets such as optimism,' said Lewina Lee, the lead author of the study at Boston University School of Medicine.

== Motivation vs Laziness

* Man goes to extraordinary lengths to invent adrenal surgery over 11 years to cure chronic condition. If he didn’t have this condition, he’d have done what everyone else does – https://fox5sandiego.com/2019/07/27/man-cures-himself-after-being-bedridden-11-years/

= Psyche & Technology

== Need for Belonging

* Social Surrogacy Hypothesis https://www.scientificamerican.com/article/imaginary-friends/
** http://dx.doi.org/10.1016/j.jesp.2008.12.003
** Jaye Derrick and http://wings.buffalo.edu/psychology/people/faculty/gabriel.html[Shira Gabriel] of the University of Buffalo and http://www.units.muohio.edu/psychology/people/hugenbk.html[Kurt Hugenberg] of Miami University test what they call the ``Social Surrogacy Hypothesis.''
** It appears that experiencing a lack of belonging actually caused people to revel in their favorite TV shows, as though the parasocial relationships with TV characters replaced the flawed relationships that had been recalled.

= How Thoughts Evolve

* If you’re young and not a socialist you have no heart, if you’re old and not a convervative have no brain.
** maximum possible ageing effect averages out at a 0.38% increase in Conservative voters per year. The minimum possible ageing effect was only somewhat lower, at 0.32% per year. https://theconversation.com/hard-evidence-do-we-become-more-conservative-with-age-47910[ref]
