:toc:
toc::[]

== Organized Religion

=== Thesis: Structure of Religion

Religions arose with agricultural. Specifically, agriculture allowed social groups in the thousands. These social groups need a mechanism to function. Religion is that mechanism. Therefore, all religions contains rules for treating followers and non-followers. Religions specify how followers can recognize each other. And religions specify how authority derives, and provide mythology for establishing identity.

All religions share the same structure:

* Laws that allow cohesion at scale.
* Holy Book that codifies laws.
* Charismatic founder who creates an institution that transcends him or her.
* Language to unify the flock.
* Rich symbolism to communicate precepts, recognize believers.
* Sacred buildings to create the sacred space.
* Rituals.
* Pilgrimates, which are rituals that involve great physical displacement towards a sacred space.
* Inheritance of divinity by representatives on Earth.

=== Cause

* agriculture generally developed around 3000 bc ex Mayans. Was it general stable Holocene climatic factors?
* Agriculture gave rise to complex societies that needed organizing structure.

=== Religious Mechanisms

Psychological mechanisms by which religions exercise control https://ffrf.org/outreach/awards/emperor-has-no-clothes-award/item/20327-steven-pinker[source]:

* Promise of life and rewards after death
* Ability to control fate through rituals and appeals to God, such as remove illness, misfortune.
* Conforming behavior is rewarded by higher powers.
* Religious practices reveal divine truths and bring believer closer to the higher power.
