:toc:
toc::[]

== Hunter Gatherers and Tribes

* Animism
** Ancestor worship
** Anything can have a spirit
** Things are interconnected
* Signs of increasing hierarchy
** Hereditary chiefship

=== Sexual Relations

* Divsion of labour - yanomamo - women do a lot of collecting of plants, and fish, and little tiny shrimps, and things like that. They make a lot of useful additions to the larder, but the men do most of the game hunting, and that requires a lot of endurance, and running, and not being hindered by babies. https://www.edge.org/conversation/napoleon-chagnon-blood-is-their-argument[Source]
** You can’t really classify the Yanomamö as monogamous, polygamous, and polyandrous. Nor do I suspect you can do that with any society, or at least societies of the sort that you’re interested in, like hunters and gatherers, transisting from hunting and gathering, to agriculture; or early agricultural societies like the Yanomamö. You have to look at marriage as a life history event. So when you’re young and don’t have a lot of kinsmen, the best game in town might be sharing a wife with your brother. So at that point your marriage is polyandrous. Then as you age, or your kinship fortunes increase—like more of your own kinsmen move to your village—then you might be able to do a wife all by yourself. And then if you become politically important and have a lot of relatives and lots of sisters to give away in marriage, you might end up with two or three wives. The most wives a Yanomamö I know has ever had is six at the same time.
** They formally acknowledge marriage.
** Big villages lord over small villages. So if you’re seeking an ally who will protect you from the people up the hill who are bigger than you, you’re at a disadvantage because in order to get allies, you’ve got to give women to them. It’s an economics game where the smaller village has to pay up front for the privileges of the alliance, and the bigger village tends to default on many of its agreements. So big villages tend to exploit small villages. It’s always a good idea to live in a big village; however, it’s like living in a powder keg.

=== Violence

* The further back in time you go, the more that unpleasant things are ubiquitous in your environment. Violence is just around the corner, and wishing for a return to the noble savage past is possibly one of the biggest errors. Pueblo houses built into the edge of the Grand Canyon, with a 1,000-foot drop below, and these houses were occupied by prehistoric Indians who were so terrified of their neighbors that they’d climb down vines and ropes with their kids on their back, and firewood under their arm, and the day’s catch in their baskets, because they were just terrified of their neighbors. And that’s the way the Yanomamö live. Even the missionaries who have lived among the Yanomamö the longest have pointed out repeatedly to me and other people that these people are terrified of neighbors. https://www.edge.org/conversation/napoleon-chagnon-blood-is-their-argument[Source]

=== Causes

* one of the things they fight over is women https://www.edge.org/conversation/napoleon-chagnon-blood-is-their-argument[Source]
* Yanomamö fight over honor. They have grudges against each other. They don’t like to fight. They prefer to be friendly, amicable, and live life in harmony. But they’re caught in a conundrum of the following sort. The only way you can live that nice happy free life is if you’re in a small community, like 25 people, most of whom are children. So everything is happy and friendly. People get along with each other. But a village of 25 people is extremely vulnerable to raids from the outside, and the men will come in and steal the women, and send the men packing, or shoot the men and take the women. So they’re constantly being pressured to maximize the size of their village. And as you increase the number of people in the village, you get increasing amounts of conflict. When the villages are attacking each other, it’s almost always for revenge. Blood is their argument. The Yanomamö will always attempt to avenge the death of a kinsman. It may take them a long time, and when the tables are turned on the guys that did it, like they get too small as a group, then it may appear to be a preemptive strike, but it has some historical roots. It’s almost never a case where they attack another Yanomamö village preemptively for no reason at all. It’s usually a consequence of some previous argument. And they’ll rejoice and say, ``I spattered his blood all over his wife, and his kids, and even his dog.''

=== Infanticide

* https://www.edge.org/conversation/napoleon-chagnon-blood-is-their-argument[Source] Infanticide: the Yanomamö practice infanticide occasionally, and it’s for a variety of reasons. One of them being if they suspect that the newborn infant is deformed, and it can be traced right back to parental investment. Why invest in a losing prospect? Let’s terminate the infant now and start anew. Another example of infanticide is, this is even rarer, that some guy was cuckolded by, or suspected he was cuckolded by some other guy, and he puts pressure on his wife to kill the new infant. That’s not very common, but I’ve heard of it.
