:toc:
toc::[]

= Nation States

== Thesis: Why Nation States Replaced Religion

Religion cannot change. Religious laws are codified in books and enforced absolutely. However, the printing press and subsequent mercantilism lead to rapidly changing conditions. Trade requires tariffs, regulations, security and so on. Given religion cannot adapt, non-religious authority emerges. Eventually, society must relegate religion and codify rules as is, without the need for divine authority. Removing divine authority means rules can change.

For further context on nation states, you’ll find it useful to read the reasons that created the https://en.wikipedia.org/wiki/Peace_of_Westphalia[Peace of Westphalia].

== Law & Order

* https://www.edge.org/conversation/napoleon-chagnon-blood-is-their-argument[Source] What about standing back and saying ``We’re avenging that death, which was caused when they avenged the previous death, and the cycle of violence keeps going on. Is there some way that we can extricate ourselves from this cycle?''
** The answer to that is in an incident when the Yanomamö began being aware of Venezuelans. It was a territorial capital 200+ miles away, and some of the missionaries sent young guys to the territorial capital to learn practical nursing to come back to the village and treat snake bites, and scratches, and wounds, and things like that, and to give them malaria pills. And they taught them how to use microscopes. But one of these guys came back and he was just terribly excited when he told me that he discovered policia. I was like, ``Well, what’s policia?'' ``They will grab people and haul them off and put them in these little separate houses, if they do something wrong. And I think we need policia, because my brother killed a man from Iwahikorobateri five years ago, and I’m always worried that the Iwahikorobateri are going to come and kill me, because he’s my brother.'' And he thought that if they had law, law would be a good thing.
* Weak states lead to local solutions to maintain order. These self-governance solutions are an example of spontaneous order.
** Dacoits/bhaggis who cite weak state and injustice to take arms: ``There are three mains reasons for someone becoming a baaghi – one, the village pradhan, two, the area thanedar and three, the patwari of the area. If these people deliver justice, no one need become a baaghi,'' he says. The uncle-nephew duo turned bandits after a property dispute with a section of the extended family turned violent and resulted in their killing two members of the other faction ``in retaliation and self defence''. https://www.hindustantimes.com/india-news/we-wouldn-t-come-charging-on-horses-like-they-show-in-bollywood-films-former-chambal-dacoits-remember-time-spent-as-bandits/story-1V8dXgX7BR50weQbN1VorJ.html[source] // Other former dacoits HT spoke to – Hari Singh Parmar, Munna Singh, Bahadur Singh – all spoke of similar disputes (often within the family) or harassment (by influential or rich people in the village or the panchayat and the authorities), as the reason for becoming dacoits. ``It was a rural economy. The only occupation was agriculture. There would be a lot of land-related disputes. When the dispute would get stuck in a revenue court or a civil court for a long time, people lost patience. In case of a fight, if a grievous crime took place, they would run away to the ravines,'' agrees Joga. // Whatever the reason, the era of the infamous Chambal dacoits seems to have passed. ``Two things have made it difficult for that kind of dacoit gangs to flourish here now ,'' says Joga. ``Roads have been constructed into the villages.'' This has made even remote areas accessible for the police, and hiding a challenge for the bandits. ``Plus, everyone has mobile phones now, so it is easier for us to get information. We have also initiated many grievance redressal mechanisms to settle disputes quickly,'' he adds.
** Second example is the early history of SF where criminal rule alternated with mob justice that finally resulted in a stable city government that provided order but also corruption.

=== Case Studies

* Africa: Scramble for Africa shows that borders were arbitrary. Data on civil conflicts after independence shows that partitioned ethnic groups suffered more warfare, more prolonged and more devastating civil wars. Civil conflict spreads from partitioned ethnicities to nearby ethnic regions. Ref: ``The Long-Run Effects of the Scramble for Africa'' Michalopoulos. http://freakonomics.com/media/Africa%20paper.pdf[Link].
* Botswana:
** https://palladiummag.com/2019/05/09/what-botswana-can-teach-us-about-political-stability/
** The arrangement we see in Botswana—where the previous head of state publicly declares a successor—solves the problem of power succession.
** Botswana avoided Cold War–driven instabilities by aligning with the West, but positioning itself such that the USSR had no interest in overthrowing it.
** Botswana was a thorn in the side of South Africa, and useful to the USSR, by sometimes allowing the communist-aligned ANC to operate in its territory.
** Ian Khama resigning from the military before entering civilian politics, rather than using the position of general to install himself directly, however, is an example of the way military leaders can acquire political power without setting a precedent for coups.
** Ian Khama resigning from the military before entering civilian politics, rather than using the position of general to install himself directly, however, is an example of the way military leaders can acquire political power without setting a precedent for coups.
** Ian Khama resigning from the military before entering civilian politics, rather than using the position of general to install himself directly, however, is an example of the way military leaders can acquire political power without setting a precedent for coups.
** government bought half of the local branch of the international De Beers corporation, rather than seizing it. Seizure is disruptive and often destroys a company’s ability to produce as the best managers and engineers flee, while purchase ensures continuity and continued production.
** Simply looking at a picture of former president Ian Khama reveals that the most prosperous ethnicity married into the traditional royal family. The marriage of President Seretse Khama, Ian’s father, was controversial at the time, likely an act of love rather than intentional statecraft. However, it was read by the white minority as a credible commitment to ethnic peace.
** The world, including its functional governments, is a lot more dynastic than we like to admit, and dynasties work a lot better at securing institutional continuity and good government than we like to think.
* Venezuela vs China in building identity and navigating global power structures:
** https://palladiummag.com/2019/05/09/what-botswana-can-teach-us-about-political-stability/
** it’s almost inconceivable that the current regime would reform Venezuela along liberal, free-market lines, as doing so would open a strong vector for U.S. influence through NGOs and market power. This would contradict how the regime conceives of itself: as an autonomy maximizer—at least with respect to America—and a social-benefits maximizer. Venezuelan state is stuck with some form of social nationalism, if it intends to maintain autonomy vis-a-vis the U.S.
** Whereas China joined the economic system, allowed sweatshops, and then beat the US at its own game by using a stronger national identity to create a more hierarchical system that moves faster than democracy’s stochastic progress.
* Kazakhstan:
** Between 1.5 and 2.3 million Kazakhs starved, the consequences of which are felt to to the present. That famine killed 40% of all Kazakhs and reduced them from 60% of Kazakhstan’s population to 38%, the highest percentage of any ethnic group killed in the Soviet Union.
** in 1991, Nazarbayev found himself the leader of the world’s 9th largest sovereign state, rich in oil and other natural resources (the country is the world’s largest producer of uranium, all for export), and with a nationally and religiously divided population.
** Nazarbayev has referred to Kazakhstan’s position as a crossroads between Europe, Asia, and the Islamic world. This is the single most important idea guiding not just Kazakh government policy, but the identity of the country itself. In Nazarbayev’s words, Kazakhstan is a country ``in the epicenter of the world,'' and Astana is the ``heart of Eurasia.'' Rhetoric is view shared by most Kazakh academics and intellectuals and has been thoroughly integrated into Kazakh cultural life and education.
** Nazarbayev has put a great deal of effort over the last 30 years into making the country Russia’s closest friend and ally. This has not only removed his greatest geopolitical threat, but has also given his country a close alliance with one of the world’s foremost powers.
** Kazakhstan maintains excellent relations with the United States and cooperates on military, economic, and counterterrorism issues. Relations with China also remain excellent, with Kazakhstan also playing a prominent role in China’s Belt and Road Initiative.
** Kazakhstan’s ``multi-vector'' foreign policy, balancing strategic relationships between the world’s great powers.
** The move of the capital city from Almaty, in the far south of the country, to Astana, was seen by many as a move to reassert Kazakh claims to the majority-Russian north. If so, it has in large part succeeded, with Kazakhs increasingly migrating to the new capital and the regions surrounding it. The largest internal and external security threat to Kazakhstan is really solving itself. Russians now only make up about 20% of the country, while Kazakhs are a healthy majority of around 65%. This is not only thanks to Russian out-migration, but also to the high birth rate in Kazakhstan, which heavily skews towards ethnic Kazakh families. In fact, while birth rates plummet across the developed world, Kazakh birthrates have steadily risen and are now higher than they ever have been in the country’s post-Soviet history, with the rate hovering around 2.7 births per woman from 2014 onward. The reasons for this trend are not absolutely clear, but likely a traditional set of social norms along with general economic success and political stability have all helped to create conditions favorable for child rearing.
** deporting dozens of foreign imams and creating an Agency for Religious Affairs staffed with party apparatchiks who have the power to appoint imams and Islamic teachers. Any crackdowns on religion in the country have been portrayed as simply a battle against `nontraditional' Islam and protective of domestic `traditional' Islam, even if in many cases this seems to just be a cover.
** Though succession is still not absolutely clear, Nazarbayev appears to be preparing to reduce his role in government. He will be celebrating his 79th birthday later this year. In 2010, Nazarbayev was declared `Leader of the Nation.' The lifetime role will protect him and his family from any prosecution, as well as giving him a broad range of powers until he dies—even if he decides not to run for president again in 2020. This means whoever becomes president next will be a kind of half-president, sharing power with Nazarbayev. In recent years he has also delegated more powers to the parliament, which is overwhelmingly controlled by his ruling Nur Otan party. Given all this, the most likely situation for succession appears to be that Nazarbayev picks his successor for president and oversees the transition while remaining firmly in control of the direction of the country in his role as Leader of the Nation. This could happen as early as 2020.
* Yugoslavia and its breakup.
* Unification of Germany.

== Change

=== Violence / Mob behavior

* Arab Spring
* Timisoara protests of 1989
* Hungary protests of 1956

== Fall

* Economic system fails at managing complexity
** Soviet Union

