Technology and Instability

= xPsyche Humans & Technology

Technology fulfills human desires.

Sometimes as part of the ``workarounds'' to make society function. Ex: TV fills our need for social connections so that we can continue to function in a world that no longer requires face-to-face interaction.

= Complexity

* Expensive typos: https://www.businessinsider.com/mistakes-and-typos-that-caused-disasters-2019-4
* Hackers infiltrate software supply chains: https://arstechnica.com/information-technology/2019/05/a-mysterious-hacker-gang-is-on-a-supply-chain-hacking-spree/
* NPM left pad broke thousands of builds:
** https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/
** A couple of hours ago, Azer Koçulu unpublished more than 250 of his modules from https://www.npmjs.com/[NPM], which is a popular package manager used by JavaScript projects to install dependencies. Koçulu yanked his source code because, we’re told, one of the modules was called Kik and that apparently https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.rrf4u36oh[attracted the attention of lawyers]representing the instant-messaging http://www.kik.com/[app] of the same name.
** Laurie Voss, CTO and cofounder of NPM, took the ``https://twitter.com/seldo/status/712414400808755200[unprecedented]'' step of restoring the unpublished left-pad 0.0.3 that apps required. Normally, when a particular version is unpublished, it’s gone and cannot be restored.
* 2019-06-16 – Argentina-Uruguay-Paraguay electricity grid failed due to single point of failure in Argentina https://www.npr.org/2019/06/16/733191328/millions-in-argentina-and-uruguay-without-electricity-after-power-failure[ref]
* 2019-06-16 – Target’s cash registers fail nationwide https://www.engadget.com/2019/06/16/target-cash-register-outage/[ref]
* 2019-06-09 - https://www.engadget.com/honda-cyberattack-suspends-global-production-140545697.html[Cyberattack] forces Honda to suspend global production for a day

== Global Optimization of Complexity

Idea: Global optimization of technological systems through owning the ecosystem allows significantly better outcomes.

* [source] Apple solved the complexity of computer chip systems by integrating all chips in one to optimize globally: "the M1 chip takes a different approach. Instead of a collection of separate processing parts, it’s a single system on a chip (SoC). The SoC handles all of the computations, including graphics output, which means that each software instruction can use the most efficient part of the M1." As a result: "General performance of the M1 MacBook Air is 3.5 times faster than before, while graphics performance is five times faster, Apple says. On the M1 MacBook Pro, AI computation is 11 times faster than before, and Apple says that it can build code in the Xcode app up to 2.8 times faster."

== Human evolved for hunter-gatherer

Lack of blue light = elongated eyeball = myopia

Ref: Nature - The Myopia Boom

= Information Society & Internet

* The abstraction of the real world into bits
* Privacy and security
* Examples
** Dog influencer ellabeanthedog
** Canadian town and bitcoin mining
* Warfare
** https://foreignpolicy.com/2019/04/27/the-spycraft-revolution-espionage-technology/[Ref] – Spycraft has completely changed. Dictatorships can parse data at will.
** Warfare is constant and low intensity. Internet anonymity allows waging war with impunity.
*** China Cloud Hopper hackers were an elaborate operation that victimized multiple Western companies: Ericsson, Fujitsu, Tata Consultancy Services, NTT Data, Dimension Data, Computer Sciences Corporation and DXC Technology.

== Examples of Technological Complexity

* Bees and neocorticoids
* Food shortages due to global warming causing Arab spring
* Trump is the first social media president combined with the effect of decades long rust belt decline etc
* Fracking in ND makes oil prices crash which causes unrest in venezuela
* Banks interlocked in ways that no one understands
* Google the world’s biggest ad provider does not create any ads, AirBnB the world’s biggest hotel doesn’t own anything etc
* Does say pollution in China lead to global warming and the Arab Spring?
* Post humanism: Replacing the hippocampus with a chip, sex change surgery, bionic eyes, live so long with such low mortality that women can choose not to have kids which fundamentally reshaped society, great recession caused by securities that no one understood
* Code is easily reconfigurable, unless physical matter. Hence, abstracting say physical photographs into a digital library is vastly superior. The architecture of the library itself can be reconfigured endlessly.
