:toc: toc::[]

== Complexity

=== Principles

* all systems get more complex over time
** impossible to roll back complexity
** thus, complexity gets too much at some point
** system must restart from scratch (revolution in society)
** OR system must add an hierarchy (neocortex + mammlian+ limbic in humans) or (religions and people in society)
*** Hierarchies add complexities of information flow
*** autonomy of agents increases at every level of hierarchy – from cell to human to priest to king
** ultimately systems try to capture all possible information about an environment
** all systems are nonlinear and scale imperfectly

=== Complexity from Simple Interactions

* Caltech researchers have shown experimentally how a simple https://phys.org/tags/network/[network] of identical synchronized nanomachines can give rise to out-of-sync, complex states.
** https://phys.org/news/2019-03-physicists-surprisingly-complex-states-emerging.html#jCp
* Climate is extremely complex. An example is the explanation for polynyas https://www.livescience.com/65693-mysterious-antarctic-ice-holes-explained.html[ref]. Stronger winds and subsequent upwelling of water -> more saline ocean surface water -> made mixing easier -> major storms mixed ocean waters more easily -> water subsurface water upwelled to melt https://www.livescience.com/65693-mysterious-antarctic-ice-holes-explained.html[ref]
* Accidental satellite collision can lead to avalanche action: 2019-09-04 ``A European satellite dodged one belonging to SpaceX over the Pacific Ocean on Monday morning, hopping around the other spacecraft after a communication glitch left SpaceX unresponsive to follow-up messages.''

==== Feedback Loops

* Systems are closed or open.
* For stability, systems need feedback.
** The Hygiene Hypothesis.
** Backpropagation in machine learning.

=== Scaling Laws

* Scaling laws dictate airplane evolution: Constructal law has also dictated the main design features needed for aircraft to succeed; the engine mass has remained proportional to the body size, the wing size has been tied to the fuselage length, and the fuel load has grown in step with the total weight. ``The same design features can be seen in any large land animal,'' said Bejan. ``Larger animals have longer lifespans and travel farther distances, just as passenger airplanes have been designed to do. For example, the ratio of the engine to aircraft size is analogous to the ratio of a large animal’s total body size to its heart, lungs and muscles.'' ``The Evolution of Airplanes,'' is authored by A. Bejan, J.D. Charles and S. Lorente. https://phys.org/news/2014-07-law-physics-airplane-evolution.html

=== Evolution of Complexity

==== Societes Compete Through Random Generation and Amplification

* Genetics: A species constantly generates individually with random traits and then amplifies the traits that survive.
* Memetics: A society constantly generates random ideas and amplifies the ideas that survive.

==== Entities Compete and Inherit

* Musical instruments inherit and are selected through ease of use, musical pleasure, and aesthestic value in performance.
* Software libraries inherits practices from each other and compete with each other.

==== Inevitable complexity increase due to Path Dependence leads to inevitable ultimately Failing

* Boeing aircraft kept in service for decades by weird modifications starts failing in a complex way: https://www.latimes.com/local/california/la-fi-boeing-max-design-20190315-story.html
** folding metal stairs attached to the fuselage that passengers climbed to board before airports had jetways. Ground crews hand-lifted heavy luggage into the cargo holds in those days, long before motorized belt loaders were widely available.
** That low-to-the-ground design was a plus in 1968, but it has proved to be a constraint that engineers modernizing the 737 have had to work around ever since. The compromises required to push forward a more fuel-efficient version of the plane — with larger engines and altered aerodynamics — led to the complex flight control software system that is now under investigation in two fatal crashes over the last five months.
** Boeing has had a good record modernizing the 737. But he said, ``They may have pushed it too far.''
** To handle a longer fuselage and more passengers, Boeing added larger, more powerful engines, but that required it to reposition them to maintain ground clearance. As a result, the 737 can pitch up under certain circumstances. Software, known as the Maneuvering Characteristics Augmentation System, was added to counteract that tendency.It was that software that is believed to have been involved in a Lion Air crash in Indonesia in October.
*** In the 737-300, which came after the original planes sold in West Germany, Boeing came up with an unusual fix: It created a flat bottom on the nacelle (the shroud around the fan), creating what pilots came to call the ``hamster pouch.''
*** ``They made it work,'' said Ditchey, whose America West was one of the original customers of the 737-300.
*** But the LEAP engines required an even bigger change. Boeing redesigned the pylons, the structure that holds the engine to the wing, extending them farther forward and higher up. It gave the needed 17 inches of clearance. The company also put in a higher nose landing gear.
*** The change, however, affected the plane’s aerodynamics. Boeing discovered the new position of the engines increased the lift of the aircraft, creating a tendency for the nose to pitch up.
*** The solution was MCAS, which ordered the stabilizer to push down the nose if the ``angle of attack'' — or angle that air flows over the wings — got too high. The MCAS depends on data from two sensors.
** The software erroneously thought the aircraft was at risk of losing lift and stalling — because of a malfunctioning sensor — and ordered the stabilizer at the rear to put it into a series of sharp dives that ultimately caused the plane to crash into the Java Sea.
* Evolution: Evolution backs iteslf into corners, called ``kludges''. For example, our spine evolves for horizontal orientation in 4 legged animals, not vertical orientation. Hence, humans experience back pain. In another example, teeth evolved to be temporary and then became permanent, but we still preserve the nerves and suffer toothaches are a result.
* Revolutions in societies -- When a society gets so complex that it can no longer evolve, then a revolution occurs to allow the society to start anew.
* Cavendish banana -- Cavendish bananas a banana cultivars. They are unable to reproduce sexually, instead being propagated via identical clones. Due to this, the genetic diversity of the Cavendish banana is very low. The extreme lack of any biodiversity and the fact the Cavendish is planted in dense chunks in a monoculture without any other natural species or plants buffering them, means the Cavendish is extremely vulnerable to disease, fungal outbreaks, and genetic mutation possibly leading to eventual commercial extinction.

=== Systems of Complex Agents (like Society)

* Trade-off between centralized power that can globally optimize and distributed power that prevents exploitation of power centers.
* A democracy implies that every agent in the system must weigh in on the final decision. This raises the question of information flows. For anti-tobacco legislation to become a priority, a majority of voters must understand the issue and its importance. This is why it took decades to pass anti-smoking laws. Because information had to flow from research to the general public. Similarly so for passing laws on global warming, immigration or any other issue. For them to pass, they must occupy public consciousness. In order to do so, people must access and understand information. Thus, a democracy ensures that progress is limited by how fast information can flow and be understood. This is the ``information bound''. So game theory leads to democracy, and democracy leads to an information bound. Ultimately, when information becomes too complex, progress will grind to a halt. Systems try to solve this problem using small world networks.

=== Examples

* See Economics doc for economic complexity.

== Network Theory

* Slime molds replicate highway networks: Transport networks are ubiquitous in both social and biological systems. Robust network performance involves a complex trade-off involving cost, transport efficiency, and fault tolerance. Biological networks have been honed by many cycles of evolutionary selection pressure and are likely to yield reasonable solutions to such combinatorial optimization problems. Furthermore, they develop without centralized control and may represent a readily scalable solution for growing networks in general. In the picture shown below, researchers have carefully placed oat flakes in the pattern of Japanese cities around Tokyo. The slime mold Physarum polycephalum was introduced, eventually connecting the flakes with an efficient network to distribute nutrients throughout the single celled organism.
