:toc: toc::[]

== Evolutionary Theory

=== Genetic Drift: Smaller Populations Evolve Faster

* The evolutionary effects of natural selection are generally independent of the size of the evolving population, while the effects of genetic drift depend strongly on population size. Other things being equal, the rate of genetic drift is proportional to the inverse square-root of population size. The inverse square-root is a simple consequence of the statistics of independent random variables. The average of any N independent random variables varies at a rate inversely proportional to the square-root of N. For any firmly established species with a population measured in millions or billions, genetic drift is negligible, natural selection is dominant, and the Darwin theory is accurately valid. For a newly emerging or endangered species with population measured in tens or hundreds, genetic drift dominates, selection is relatively unimportant, and the Kimura theory is valid. The random jumps of genes in a small population produce evolutionary change much faster than the gentle push of natural selection. Kimura understood that genetic drift is the main driving force in the quick jumps when species are created or extinguished.
** https://www.edge.org/conversation/freeman_dyson-biological-and-cultural-evolution
** Nature thrives by taking risks. She scrambles mating-system genes so as to increase the risk that individual parents will fail to find mates. The increase of risk of sterility of individuals is a part of Nature’s plan. She imposes the increased risk on the whole population, so that a rare event will occur with greater probability, when a pair of lucky parents, whose names might happen to be Adam and Eve, are born with matching mating-system mutations. That rare event gives a pair of parents a chance to give birth to a new species.

=== Sex genes rapid evolution

Goodenough concludes that the rapid mutation of mating-system genes is Nature’s way of achieving big jumps in large-scale evolution. Rapidly evolving mating systems gave us the diversity of species that astonished Darwin. Twenty years ago, Goodenough wrote a paper with the title, ``Rapid Evolution of Sex-related Genes'', describing her observations and conclusions.

=== Long Tail Events

* Meteorites cause explosions
* Mongols destroyed Baghdad and allowed eventual European power.
* Fukushima halted nuclear power even though no one died from radiation exposure.
* Tambora explosion changed human history. ``The first great wave of emigration from Ireland began at the time of the Tambora crisis. Emigration from England and Scotland also rose sharply in 1816. Building of the Erie Canal''. https://nypost.com/2019/07/27/how-an-1815-volcanic-eruption-turned-new-york-into-americas-largest-city/

== ML and Evolution

=== Dropout and Ev

Paper: http://jmlr.org/papers/volume15/srivastava14a/srivastava14a.pdf

One possible explanation for the superiority of sexual reproduction is that, over the long term, the criterion for natural selection may not be individual fitness but rather mix-ability of genes. The ability of a set of genes to be able to work well with another random set of genes makes them more robust. Since a gene cannot rely on a large set of partners to be present at all times, it must learn to do something useful on its own or in collaboration with a small number of other genes. According to this theory, the role of sexual reproduction is not just to allow useful new genes to spread throughout the population, but also to facilitate this process by reducing complex co-adaptations that would reduce the chance of a new gene improving the fitness of an individual. Similarly, each hidden unit in a neural network trained with dropout must learn to work with a randomly chosen sample of other units. This should make each hidden unit more robust and drive it towards creating useful features on its own without relying on other hidden units to correct its mistakes. However, the hidden units within a layer will still learn to do different things from each other. One might imagine that the net would become robust against dropout by making many copies of each hidden unit, but this is a poor solution

=== MWUA and evo

Source: Papadimitriou - Algorithms, complexity, and the sciences

the equations of population genetic dynamics are mathematically equivalent to positing that each locus selects a probability distribution on alleles according to a particular rule which, in the context of the theory of algorithms, game theory, and machine learning, is known as the multiplicative weight updates algorithm (MWUA). MWUA is known in computer science as a simple but surprisingly powerful algorithm (see ref. 5 for a survey). Moreover, there is a dual view of this algorithm: each locus may be seen as selecting its new allele distribution at each generation so as to maximize a certain convex combination of (i) cumulative expected fitness and (ii) the entropy of its distribution on alleles. This connection between evolution, game theory, and algorithms seems to us rife with productive insights; for example, the dual view just mentioned sheds new light on the maintenance of diversity in evolution
