:toc: toc::[]

Computation

= Abstracting real-world

* The Matrix
* Wired: Mirror world concept where things exist in cyberspace
* Eve Online
** Battle of b-r5rb

== Modeling & Simulations

* In a description, returns do not scale with description complexity. You have to make your description more and more complex to improve your description. Ultimately, you realize you need a simulation from first principles. Ex. using bisection to iteratively find a root.
* http://mcs.open.ac.uk/mj665/icse17kn.pdf[source]
** von Neumann’s Principle - Establishing the vocabulary of ground terms that we will use in talking about the world and the machine. If  want to assert that: For each novel x there is a unique writer y that is the author of the novel. then we had better say, and say precisely, what we mean by ‘x is a novel’, what we mean by ‘y is a writer’, and what we mean by ‘y is the author of x’.
** The Principle of Reductionism - In a library administration system it seems obviously right to choose member as a ground term. But almost certainly these choices are serious errors. In the library system, being a member is a state of an individual who has enrolled in the library and has not yet resigned or lapsed or been expelled. The events enrol, resign, lapse, and expel are probably appropriate ground  — that is, designated phenomena. The ground terms you should be concerned with are, as often happens, events. Picking up a telephone handset,replacing it, dialling a digit, starting to receive a busy tone — all these are readily recognisable phenomena. So too are take-off and landing events in the life of an aeroplane, and boarding and disembarking events in the life of a passenger. These should be your ground terms. If you can reconstruct calls and flights by definitions using these ground terms, well and good.
** Shanley's Principle - This versatility and many-sidedness, both of larger
structures and of elementary individuals, must be reflected in an appropriate approach to describing and understanding the world. At the level of domain description and problem analysis it demands parallel structuring of views and problems. The parallel decomposition of a colour picture into Cyan, Magenta, Yellow and Black colour separations is a far better metaphor for structuring than the hierarchical bill of materials assembly structures that have been the staple fare of elementary problem solving for far too long. At the elementary level we must recognise similarly that the world is not strongly typed. It is always possible to devise a very restricted view of the world in which elementary individuals can be classified into disjoint sets and strongly typed. But such a view is always far too restricted to capture a problem of serious interest, and many such views must be adopted simultaneously. The elementary individuals in one view then appear, differently classified and differently typed, in other views. The need for multiple viewpoints is felt at the elementary level too.
** Montaigne’s Principle - The indicative mood expresses what we assert to be true; the optative mood expresses what we desire to be true. For the developers of the system to control reverse thrust the statement: REQ: can_rev ↔ on_runway i  in the optative mood. It expresses what they desire to be true, the effect that their system is to bring about in the world. But the statement: WORLD1: pulsing ↔ rotating is in the indicative mood. It expresses what they assert to be true of the world, regardless of the behaviour of the system they are building. A better approach is to avoid grammatical distinctions of mood within a single description, and to indicate the mood of a description by its place in the whole development structure. One penalty for ignoring the distinction between indicative and optative is the confusion often felt by readers of formal specifications. Some formal specifications abstract from the distinction between the different moods. The formal specification is a homogeneous description of the behaviour of the correctly implemented machine interacting with the world. Behavioural properties attributable to indicative truths about the world are not distinguished from properties attributable to the satisfaction by the machine of the customer’s optative requirements. A predicate P is given as the precondition on an operation O, but we are not told whether:
*** the machine will inhibit O if P does not hold; or
*** the world ought to refrain from invoking O when P
does not hold; or
*** the world is known never to invoke O when P does not hold.

== Incompleteness Theorems

* Incompleteness theorem has different manifestations in different fields.
** Price of anarchy
** Uncertainty principle
** Halting problem
